import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AppContextProvider } from "./components/AppContext";
import GlobalHeader from "./components/globalHeader/globalHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('RootLayout reload')
  return (
    <html lang="zh">
      <body>
        <AppContextProvider>
          <GlobalHeader />
          <div className="globalContent">
            <div className="content-core">
              {children}
            </div>
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
